### ISSUE TITLE
Dead URL (kite.black)

### ISSUE THREAD

**Issue by mmorella-dev** [callmearta/kite#15]
The domain registration for <https://kite.black> appears to have expired; it points to a parked domain.

**Comment by callmearta** [comment]
Yes. It did expire a few months ago since I wasn't able to afford renewing it. Feel free to clone it and run it locally.

**Comment by mmorella-dev** [comment]
Understandable. I would suggest removing the abandoned URL from the README and project description, to avoid the risk of accidentally pointing people at unintended content.

**Comment by callmearta** [comment]
Well said. I did inform people on the Bluesky itself but forgot to change description in here. Thanks for reminding.
