### ISSUE TITLE
Dark/ light mode switch on mobile

### ISSUE THREAD

**Issue by kjarex** [callmearta/kite#3]
Maybe I'm just blind, but is it possible that the button for dark/light mode switching is missing in the mobile view? 

I wasn't sure where even to expect it (would fit in at view spots), but I tried to check everywhere but couldn't find it.

It's not impossible that it's a browser-related bug, but I didn't miss anything else, so I don't expect it to be (even though it could still be just the only browser-related bug). So if relevant: used Chrome on Android 10(can it be? Phone is 2 yrs old!?) as well as the Duck(.com) browser (and whatever engine it uses)

**Comment by callmearta** [comment]
Yea it's not a bug and neither you've gone blind. I've hidden it for now on mobile since i plan to do a simple overhaul for it. It'll be added when the new UI arrives
