### ISSUE TITLE
What's hot

### ISSUE THREAD

**Issue by kjarex** [callmearta/kite#4]
This isn't a bug report (anymore). I had been wondering how to get "What's hot" back after it was closed. If figured it out before I eventually got on Github.

Just as a thought (not a request, nor even a real suggestion): 
I do like that it integrates smoothly and doesn't draw much attention. But it's maybe TOO easy to miss it currently. So maybe put the flame on a button or something like that? Absolutely possible that no one else runs into this issue (if it's really just me then just ignore this, because I am now aware of it). 👍

**Comment by callmearta** [comment]
Yes i'll try to make it a bit more visible
