### ISSUE TITLE
Clear cache/Logout suggestion

### ISSUE THREAD

**Issue by kjarex** [callmearta/kite#5]
Unavailable servers are currently a non-issue, so this is a "nice to have" of no urgency, but… 

If Kite was connected to a server which is currently not available, you can't logout (in order to connect to a different server), as Kite will try to reconnect but can't.

Once you deleted the cache it works as expected. Would be nice to just add a "logout" page, which simply clears the cache (accessible via `/logout`, that's what most web apps use and what I tried intuitively) - as you might be on a system which doesn't allow to clear the cache (easily), like maybe kiosk terminals, smart TVs/ fridges, …

**Comment by callmearta** [comment]
there's exactly a /logout route specified for doing this action :))

**Comment by kjarex** [comment]
It doesn't work for me 😐
It just reloads the page (well, just for opening a new URL kinda) and then I'm still logged in. 
Just tried it this very moment again (it's still on the /logout address, but I'm logged in, see all posts, could post sth, etc)

**Comment by callmearta** [comment]
Sorry for the confusion. I was confused as well. It's url is kite.black/#/logout . Since it's running on GH pages that hash is necessary in the url and i have forgotten about it
