### ISSUE TITLE
Consider removing the 'Blocks' tab from a profile

### ISSUE THREAD

**Issue by ghost** [callmearta/kite#9]
Hey there, first of all great job with the client, it really brings some freshness needed to Bsky.

One thing that bothers me a bit  is the fact that there's a 'Blocks' tab on the profiles and anyone can see the users I have blocked. I understand that this is public information on Bluesky, but displaying the block list like might expose the user to more harassment.

The official client doesn't expose this in their interface, another popular tool (wolfgang.raios.xyz) removed their blocks list as well. 

I like Kite and I want to recommend to my friends, but I can't recommend a client that enables harassment instead of fighting it.

I can open a pull-request if you want. :)

**Comment by kjarex** [comment]
I agree that public blocks are a bad idea. But I think the tab is a good thing as everyone needs to be aware and reminded at all times, that they are public.

One might say, bad actors shouldn't be provided with tools, which make it easier to act in a bad way, but they will have those tools anyway (even if the bad actor has no technical skills). They simply would google how to view the block list and get a link to those tools anyway.

It would only make sense, if you could guarantee that (absolutely) every clients will remove this ability, which is imo a goal which won't/can't be achieved. It only needs one bad actor with (some) technical skills, and those tools will be available.

**Comment by callmearta** [comment]
I think this issue is no longer valid since @kjarex answered it totally right
